services:
  - type: web
    name: mm-backend
    env: node
    buildCommand: "npm install && npm run build" # Bağımlılıkları yükleyip sonra build işlemini başlatır
    startCommand: "npm start"
envVars:
      - key: JAVA_HOME
        value: "/usr/lib/jvm/java-11-openjdk-amd64"
