services:
  - type: web
    name: mm-backend
    env: node
    buildCommand: |
      # Gerekli derleyici ve bağımlılıkları yükle
      sudo apt-get update -y
      sudo apt-get install -y build-essential python3

      # Java'yı yükle
      sudo apt-get install -y openjdk-11-jdk

      # JAVA_HOME ortam değişkenini ayarla
      export JAVA_HOME="/usr/lib/jvm/java-11-openjdk-amd64"

      # Bağımlılıkları yükle
      yarn install
    startCommand: "npm start"
    envVars:
      - key: JAVA_HOME
        value: "/usr/lib/jvm/java-11-openjdk-amd64"
